version: "3.6"

services:
  postgres:
    image: postgres:13
    restart: always
    ports: 
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: test
    volumes:
      - /tmp/postgres:/postgres/data
  redis:
    image: redis:latest
    restart: always
    ports: 
      - "6379:6379"
    volumes:
      - /tmp/redis:/redis/data